version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: movie_search_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sakila
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./sakila-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: movie_search_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://db:3306/sakila?serverTimezone=UTC&useSSL=false
      DB_USER: admin
      DB_PASS: password
      TESSDATA_PATH: /usr/share/tesseract-ocr/4.00/tessdata
    ports:
      - "8080:8080"
