# version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:       sakila
      MYSQL_USER:           admin
      MYSQL_PASSWORD:       password
    ports:
      - "3306:3306"
    volumes:
      - ./sakila-db:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
